- name: Download and Install ENB archive
  unarchive:
    remote_src: yes
    src: https://arm.mo.ca.am.ericsson.se/artifactory/simple/proj-enb-release-local/com/ericsson/enb/enb-parent/{{ enb_version }}/ENB_Linux64_CXP9027591_3_{{ enb_version }}.tar.gz
    dest: /opt/
    creates: /opt/ENB_{{ enb_version }}

- name: Install startup script
  template:
    src: enb
    dest: /usr/local/bin/enb
    mode: "ugo+x"
