#Uses node:12.2.0-alpine
FROM node:12.2.0-alpine

#Create app directory
RUN mkdir -p /app
WORKDIR /app

#Copy package.json into app directory 
COPY package.json /app

#Run yarn install to install all the dependencies 
RUN yarn install

#Copy all the files into app
COPY . /app

#Build the app with yarn
RUN yarn build

#Execute the code with yarn start
CMD [ "yarn", "start" ]