# Generated by Django 2.0 on 2019-10-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosite_api', '0002_auto_20191010_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='student',
            name='style',
        ),
    ]
