version: '3'

services:
  server:
    build: context/server

    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/home/${LOCALUSER}/git:/root/git"
    #  - "/vagrant/package/.m2:/root/.m2"
      - "/etc/timezone:/etc/timezone"
      - "${JENKINS_CI_LIB_DIR:-../../jenkins-ci-lib}:/jenkins-ci-lib"
    ports:
      - "8081:8080"

  slave:
    #build: context/slave
    image: armdocker.rnd.ericsson.se/proj-afg/rbt_compilation_ub_18:v2
    volumes:
      - "workspace:/workspace"
      - "/home/${LOCALUSER}/git:/root/git"
      #- "/vagrant/package/.m2:/root/.m2"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone"
      - "${JENKINS_CI_LIB_DIR:-../../jenkins-ci-lib}:/jenkins-ci-lib"
    ports:
      - "8122:22"

  localrepo:
    image: registry:latest
    container_name: localrepo
    volumes:
      - registry:/var/lib/registry
    ports:
      - "50000:5000"

volumes:
  jenkins_home:
  workspace:
  registry: