# See: https://microk8s.io/#
# Docs: https://github.com/ubuntu/microk8s

- name: Install microk8s
  shell: snap install microk8s --classic

- name: Add snap aliases to the main microk8s commands
  shell: snap alias {{item.cmd}} {{item.alias}}
  with_items:
    - { cmd: "microk8s.docker", alias: "docker" }
    - { cmd: "microk8s.istioctl", alias: "istioctl" }
    - { cmd: "microk8s.kubectl", alias: "kubectl" }

- name: Create bash_aliases file
  become_user: "vagrant"
  file:
    path: /home/vagrant/.bash_aliases
    state: touch

- name: Add short shell aliases
  become_user: "vagrant"
  lineinfile:
    path: /home/vagrant/.bash_aliases
    regexp: "^alias {{item.alias}}="
    line: "alias {{item.alias}}={{item.cmd}}"
    state: present
    create: yes
  with_items:
    - { alias: "d", cmd: "docker" }
    - { alias: "i", cmd: "istioctl" }
    - { alias: "k", cmd: "kubectl" }


- name: Install kubectl shell completion
  become_user: "vagrant"
  lineinfile:
    path: /home/vagrant/.profile
    state: present
    create: yes
    line: "source <(kubectl completion bash)"

# See: https://github.com/cykerway/complete-alias
- name: Install alias bash completion utility
  become_user: "vagrant"
  get_url:
    url: https://raw.githubusercontent.com/cykerway/complete-alias/master/completions/bash_completion.sh
    dest: /home/vagrant/.bash_completion

- name: Add bash completion to aliases
  become_user: "vagrant"
  lineinfile:
    path: /home/vagrant/.bash_completion
    state: present
    create: yes
    line: "complete -F _complete_alias {{item}}"
  with_items:
    - "k"
    - "i"

- name: Fix ip tables warning reported by microk8s.inspect
  shell: iptables -P FORWARD ACCEPT

- include_tasks: istio.yml
  when: microk8s_enable_istio
