# Installs git extensions, adding new commands to git.

- name: create tools directory
  become_user: "{{ username }}"
  file:
    path: /home/{{ username }}/tools
    state: directory
 
- name: Get gitext
  become_user: "{{ username }}"
  git:
    repo: ssh://gerrit.ericsson.se:29418/eme/gitext.git
    dest: /home/{{ username }}/tools/gitext
    update: no
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Remove user's existing environment variables
  become_user: "{{ username }}"
  lineinfile:
    path: /home/{{ username}}/.profile
    state: absent
    regexp: "{{ item }}"
  with_items:
    - "^export PATH=.*gitext/bin.*"

- name: Setup PATH
  become_user: "{{ username }}"
  lineinfile:
    path: /home/{{ username }}/.profile
    line: "export PATH=${HOME}/tools/gitext/bin:${PATH}"
    state: present
    create: yes
