# Jenkins slave with sshd and docker client installed.
FROM armdocker.rnd.ericsson.se/proj-afg/rbt_compilation_slave_ubuntu:v1
#FROM ubuntu:16.04

RUN apt-get update && \
  apt-get -y install apt-transport-https \
  vim \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common && \
  curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
  add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
  $(lsb_release -cs) \
  stable" && \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get -y install docker-ce openssh-server oracle-java8-installer 

#install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
#RUN apt-get -y install docker-compose
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile" 
ENV JAVA_HOME=/usr/lib/jvm/java-8-oracle 

RUN echo "export VISIBLE=now" >> /etc/profile

#START

ENV MAVEN_VERSION 3.3.9
# Enables signals getting passed from startup script to JVM
# ensuring clean shutdown when container is stopped.

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

#END

VOLUME /workspace

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
