- name: install react-native binary x64 dependencies
  command:
    sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

# The EDS http://eds.rxn.us/ icons are provided as a font, this utility https://github.com/oblador/react-native-vector-icons helps integrating those icons to the project.
- name: install react-native-vector-icons for eds icon font setup
  command:
    npm install -g react-native-vector-icons

- file:
    path: /home/{{ username }}/eds/bin/
    state: directory

# Add the EDS fonts http://eds.rxn.us/public/zip/fonts/fonts.zip
- name: add the eds fonts
  unarchive:
    src: http://eds.rxn.us/public/zip/fonts/fonts.zip
    dest: /home/{{ username }}/eds/
    remote_src: yes

# Add the EDS style sheet http://eds.rxn.us/public/zip/styles/styles.zip
- name: add the eds css
  unarchive:
    src: http://eds.rxn.us/public/zip/styles/styles.zip
    dest: /home/{{ username }}/eds/
    remote_src: yes


- name: copy the init script for EDS react-native
  copy:
    src: react-native-eds.sh
    dest: /home/{{ username }}/eds/bin/
    mode: u+rwx,g+rx,o+rx

- name: Add eds bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/eds-path.sh
    content: 'PATH=$PATH:/home/{{ username }}/eds/bin/'